[package]
name = "runtimes-macro"
version = "0.1.0"
authors = ["Eric Sheppard <eric@eigenmo.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"
darling = "0.14"
proc-macro2 = "1"
