version: "3"
services:
  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"

  mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
