version: "3"
services:
  mssql-2022:
    build:
      context: docker/
      dockerfile: docker-mssql-2022.dockerfile
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"

  mssql-2019:
    build:
      context: docker/
      dockerfile: docker-mssql-2019.dockerfile
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"

  mssql-2017:
    build:
      context: docker/
      dockerfile: docker-mssql-2017.dockerfile
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"

  mssql-azure-sql-edge:
    build:
      context: docker/
      dockerfile: docker-azure-sql-edge.dockerfile
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
